package ai.onnxruntime.example.imageclassifier

import ai.onnxruntime.*
import android.content.Context
import android.graphics.Bitmap
import android.graphics.ColorSpace
import android.graphics.Matrix
import android.os.SystemClock
import android.util.Log
import androidx.camera.core.ImageAnalysis
import androidx.camera.core.ImageProxy
import org.opencv.core.*
import org.opencv.core.CvType.CV_8UC3
import org.opencv.core.CvType.CV_8UC4
import org.opencv.dnn.Net
import java.io.File
import java.io.IOException
import java.lang.reflect.Type
import java.nio.ByteBuffer
import java.nio.FloatBuffer
import java.text.DecimalFormat
import java.util.*
import kotlin.jvm.internal.Ref
import kotlin.math.exp
import kotlin.math.max